# Automated dependency management configuration
# Security vulnerabilities: Immediate PR creation (overrides schedule)
# Regular updates: Weekly on Mondays 09:00 JST
# Target: develop branch for staged testing
version: 2
updates:
  # npm dependencies - Phase 1
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "develop"
    reviewers:
      - "yukifrog"
    assignees:
      - "yukifrog"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Critical production dependencies (security updates: immediate)
      critical-dependencies:
        patterns:
          - "next"
          - "react*"
          - "prisma"
          - "@prisma/*"
          - "next-auth"
          - "@auth/*"
        update-types:
          - "minor"
          - "patch"
      
      # Standard production dependencies (security updates: immediate)
      standard-dependencies:
        patterns:
          - "chart.js"
          - "@types/*"
          - "nodemailer"
        update-types:
          - "minor"
          - "patch"
          
      # Development dependencies (security updates: immediate)
      development-dependencies:
        patterns:
          - "eslint*"
          - "prettier"
          - "@playwright/*"
          - "typescript"
          - "jest*"
          - "@testing-library/*"
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions - Phase 2
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
    target-branch: "develop"
    reviewers:
      - "yukifrog"
    assignees:
      - "yukifrog"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Action updates grouped by category
      setup-actions:
        patterns:
          - "actions/checkout*"
          - "actions/setup-node*"
          - "actions/cache*"
        update-types:
          - "minor"
          - "patch"
          
      test-actions:
        patterns:
          - "github/codeql-action*"
          - "actions/upload-artifact*"
          - "actions/download-artifact*"
          - "actions/github-script*"
        update-types:
          - "minor"
          - "patch"
